### PR TITLE
Add missing `form-data` module

### LINKED ISSUE #12: error starting Homebridge .4.50
Hi,

I have this issue:

[2019-9-13 18:21:12] Loaded config.json with 0 accessories and 1 platforms.
[2019-9-13 18:21:12] ---
[2019-9-13 18:21:12] Loaded plugin: homebridge-camera-ui
module.js:550
    throw err;
    ^

Error: Cannot find module 'form-data'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:14:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

### PR DESCRIPTION
**Pull request by designorant**
Fixes #12

### CODE REVIEW

**Comment by overflywingo** [comment]
Hi, sorry for my (linux) ignorance .. but how to do to add missing "form-data" module ?

**Comment by designorant** [comment]
@overflywingo Assuming you're running a standard config:

1. Go to `homebridge-camera-ui` dir: `cd /usr/local/lib/node_modules/homebridge-camera-ui`
2. Install `form data` there: `npm install form-data --save` (you may need to use `sudo` before this command in case it fails)

**Comment by overflywingo** [comment]
Excellent ! Thank you Michal

Everthing's OK now :-)

**Comment by montanaishome** [comment]
Thanks!  This fixed my issue.

**Comment by donavanbecker** [comment]
@SeydX will we see a new version? or any other PRs merged?

**Pull request merged**
